window.APP_CONFIG = {
  sheetId: "1T5O2wbpeilVbVxfkzpthYs73Ms4uJvbu0YAQe4TfUS8",
  sheetUrl: "https://docs.google.com/spreadsheets/d/1T5O2wbpeilVbVxfkzpthYs73Ms4uJvbu0YAQe4TfUS8/edit?usp=sharing",
  sheetMode: "csv",
  range: "Sheet1!A:E",
  apiKey: "",
  cardsTab: "Cards",
  heroTab: "Hero",
  featuredEventsTab: "FeaturedEvents",
  previousEventsTab: "PreviousEvents",
  upcomingEventsTab: "UpcomingEvents",
  countriesTab: "Countries",
  venuesTab: "Venues",
  countryPicsTab: "Country Pics",
  testimonialsTab: "Testimonials",
  partnersTab: "Partners",
  newsletterTab: "Newsletter",
  collaborateTab: "Collaborate",
  heroDesktopCol: "2",
  heroMobileCol: "3",
  heroActiveCol: "4",
  heroRotationMs: "7000",
  geoEndpoint: "https://ipapi.co/json/",
  registerUrl: "https://form.typeform.com/to/kkuhy7ob",
  newsletterEndpoint: "https://script.google.com/macros/s/AKfycbzctuxuhi2ocO-rwocI6Ph5fFSqHv5CJ33IZdWXJ3fFQ7c1y-mNofQ_SjX2rnK--E-4uQ/exec",
  collaborateEndpoint: "",
  newsletterFormUrl: "",
  newsletterFormFirstNameField: "",
  newsletterFormLastNameField: "",
  newsletterFormCountryField: "",
  newsletterFormEmailField: "",
};
