window.APP_CONFIG = {
  sheetId: "1T5O2wbpeilVbVxfkzpthYs73Ms4uJvbu0YAQe4TfUS8",
  sheetUrl: "https://docs.google.com/spreadsheets/d/1T5O2wbpeilVbVxfkzpthYs73Ms4uJvbu0YAQe4TfUS8/edit?usp=sharing",
  sheetMode: "csv",
  range: "Sheet1!A:E",
  apiKey: "",
  cardsTab: "Cards",
  heroTab: "Hero",
  countriesTab: "Countries",
  venuesTab: "Venues",
  countryPicsTab: "Country Pics",
  testimonialsTab: "Testimonials",
  partnersTab: "Partners",
  heroDesktopCol: "2",
  heroMobileCol: "3",
  heroActiveCol: "4",
  heroRotationMs: "7000",
  geoEndpoint: "https://ipapi.co/json/",
  registerUrl: "https://docs.google.com/forms/d/e/1FAIpQLSectYAdjAU05va9eshykh6h8LgGKeG7d-Hm190bpSbz3l7EJQ/viewform",
};
